### ISSUE TITLE
Weights for regional/global means

### ISSUE THREAD

**Issue by katiedagon** [NCAR/ctsm_python_gallery#17]
From briefly surveying the group, it seems that there are several approaches to calculating weighted regional and global means of land model output. Moving to python provides an opportunity to standardize the approach. 

This issue was inspired by the area_wgt variable in SimpleExample.ipynb (is there a better way to reference specific lines in a notebook on github?), and the desire to replicate the behavior of NCL functions like [wgt_areaave](https://www.ncl.ucar.edu/Document/Functions/Built-in/wgt_areaave.shtml) and [wgt_areaave2](https://www.ncl.ucar.edu/Document/Functions/Built-in/wgt_areaave2.shtml).

**Comment by ckoven** [comment]
here's how i have been doing this (dependent on pyngl):

https://github.com/ckoven/ckplotlib/blob/master/geog_funcs.py#L109
